ros2/realtime_support

- CMakeLists.txt
- include/rttest/rttest.h
- scripts/get_average_jitter.py
- src/rttest.cpp
initial implementation of the header laid out in the master branch.
Some highlights:
See "examples/example_loop" for a common usage of this library.
Argument parsing and initial memory allocation is taken care in `rttest_read_args`.
The code to be instrumented is passed as a function pointer to `rttest_spin`, which calls the function and measures scheduling jitter and pagefaults in a real-time safe way.
Teardown happens in `rttest_finish`.
`rttest` keeps track of statistics and stores parameters for different threads, but the interface to rttest does not expose the thread. It keeps an internal struct to check the thread id of the calling thread and gets/sets data for that thread accordingly.
> initial implementation

- CMakeLists.txt
- README.md
- examples/example_loop.c
- include/rttest/rttest.h
- include/rttest/utils.h
- package.xml
- src/rttest.cpp
- test/test_api.cpp
http://ci.ros2.org/job/ros2_batch_ci_linux/236
http://ci.ros2.org/job/ros2_batch_ci_osx/155
http://ci.ros2.org/job/ros2_batch_ci_windows/238
> Add gtests, comply to uncrustify, don't build on Windows

- CMakeLists.txt
- rttestConfig.cmake.in
This is necessary to build successful when only OpenSplice is present.
The CMakeLists.txt contains a lot of redundant code but that should be cleaned up in a separate PR.
> fix linking against pthread

- src/rttest.cpp
I broke the build in the last PR (style warning for using free after new).
http://ci.ros2.org/job/ros2_batch_ci_linux/277/
> Fix mismatched alloc/dealloc

- CMakeLists.txt
- scripts/rttest_plot
Install the `rttest_plot` script so that the user can easily plot the results of an rttest run.
> Install rttest_plot script

- CMakeLists.txt
Use `install(PROGRAMS...)` to install the scripts with the right permissions.
Fixes #10
> Install rttest_plot and analyze.py as programs

- rttest/src/rttest.cpp
While looking for some other failing tests I found this which looks like a wrong boundary check.
> fix boundary check

- tlsf_cpp/CMakeLists.txt
- tlsf_cpp/test/test_tlsf.cpp
This change allows better Jenkins reporting of the test results, e.g. to avoid a report like this:
http://ci.ros2.org/job/ci_linux/807/testReport/%28root%29/AllocatorTest/
wherein you can't tell which implementation was used in which test (you could, of course, still get that info from the console output).
> add rmw impl suffix to test names

- rttest/include/rttest/rttest.h
- rttest/src/rttest.cpp
Connect to #21.
http://ci.ros2.org/job/ci_linux/817/
> fix memory management of rttest_sample_buffer

- tlsf_cpp/test/test_tlsf.cpp
Follow up of #19.
Apply the class name suffix actually to the class name and not to the function name.
> fix name of test class

- rttest/examples/example_loop.c
- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
Probably won't fix the mysterious memory issues reported in #21 (if they still persist; I wasn't able to reproduce the segfault). If a filename is given on the command line, allocate it on the heap and deallocate it on cleanup. Also, check if the allocated pointer is NULL whenever `malloc` is called.
> Store filename string on the heap

- tlsf_cpp/CMakeLists.txt
Without this, building against tlsf_cpp causes a link error.
> Export tlsf package

- rttest/include/rttest/utils.h
a few trivial tweaks to ensure we get 64-bit calcuation of time multiplications and diffs
> uint32 -> long in a few places for time calculation

- tlsf_cpp/test/test_tlsf.cpp
There was an extraneous `Executor` instantiated in this test which was causing a problem in my `fixed_guard_conditions` branch, because the `AllocatorMemoryStrategy` object was shared between the two objects.
> Remove extraneous argument in test

- tlsf_cpp/CMakeLists.txt
`${PROJECT_NAME}` is not a valid target in this CMake file as far as I can see.
> remove non-existent target dependency

- tlsf_cpp/include/tlsf_cpp/tlsf.hpp
- tlsf_cpp/test/test_tlsf.cpp
Connects to #37
**Do not merge until we update to Xenial; this will break the build with the default gcc on Trusty.**
> Clean up allocator for gcc 5.3

- rttest/CMakeLists.txt
- tlsf_cpp/CMakeLists.txt
`rttest` must not rely on internal implementation details but use a variable to use the list of libraries in multiple places.
Since `tlsf_cpp`doesn't export any libraries using these variables doesn't make any sense.
Please review.
> remove usage of internal variables and noops

- tlsf_cpp/CMakeLists.txt
> Consistent naming when using CMake variable for rmw implementation

- tlsf_cpp/package.xml
follow up of https://github.com/ros2/examples/pull/134#discussion_r88093240
depends on https://github.com/ament/ament_tools/pull/124
> no need for test_depend if already exec_depend

- tlsf_cpp/package.xml
Bloom complains that this package and rttest which share the repository must have the same version in package.xml.
https://github.com/ros2/realtime_support/blob/ca3c8eb993245c4ad3b368e1158c630e405ab5e3/rttest/package.xml#L5
Should I run CI for this? as far as I know version constraints don't affect the build but I have been wrong before.
> Bump version for package consistency within repo.

- tlsf_cpp/package.xml
When [building this package](http://build.ros2.org/view/Rbin_uX64/job/Rbin_uX64__tlsf_cpp__ubuntu_xenial_amd64__binary/1/console#console-section-1) we got the following failure.
```
13:41:35 CMake Error at CMakeLists.txt:20 (find_package):
13:41:35   By not providing "Findstd_msgs.cmake" in CMAKE_MODULE_PATH this project has
13:41:35   asked CMake to find a package configuration file provided by "std_msgs",
13:41:35   but CMake did not find one.
13:41:35 
13:41:35   Could not find a package configuration file provided by "std_msgs" with any
13:41:35   of the following names:
13:41:35 
13:41:35     std_msgsConfig.cmake
13:41:35     std_msgs-config.cmake
13:41:35 
13:41:35   Add the installation prefix of "std_msgs" to CMAKE_PREFIX_PATH or set
13:41:35   "std_msgs_DIR" to a directory …
```
> Add missing dependencies on rmw and std_msgs.

- tlsf_cpp/test/test_tlsf.cpp
test_tlsf__rmw_opensplice_cpp fails with OpenSplice on AArch64 (http://ci.ros2.org/job/ci_linux-aarch64/974/)
I found that it fails because the [check_stacktrace](https://github.com/ros2/realtime_support/blob/master/tlsf_cpp/test/test_tlsf.cpp#L97) function returns fail.
The [tokens](https://github.com/ros2/realtime_support/blob/master/tlsf_cpp/test/test_tlsf.cpp#L43) list used by this function included fastrtps but not opensplice.
> fix test_tlsf__rmw_opensplice_cpp

- rttest/README.md
RTLinux is obsolete, and both commercial and GPL editions were no longer
maintained. Through the use of the real-time Linux kernel patch
PREEMPT_RT, support for full preemption of critical sections, interrupt
handlers, and "interrupt disable" code sequences can be supported.
> Drop obsolete RTLinux

- rttest/CMakeLists.txt
> install headers into the same location when ament_cmake is not used

- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
Fix armhf build warnings caused by incorrect format specifiers.
Build warnings: [src](https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/36/warnings23Result/package.767540328/) and [test](https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/36/warnings23Result/package.-1976035698/)
Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>
> Fix armhf build warnings

- rttest/include/rttest/rttest.h
- rttest/src/rttest.cpp
We were previously storing the nanosecond latency in an int.
However, it is pretty easy to overflow with nanoseconds; anything
above around 2 seconds will overflow.  Switch to an int64_t
everywhere, which gives us a much larger range to work with.
> Switch the latency storage to int64_t.

- rttest/src/rttest.cpp
Last column in output file is mislabeled  as `minor_pagefaults`
Signed-off-by: Servando <servando.german.serrano@linaro.org>
> Fix typo in the header of output file

- tlsf_cpp/test/test_tlsf.cpp
See: https://github.com/ros2/realtime_support/pull/80#issuecomment-545162609
> disable intra process test until intra process manager fixed up

- tlsf_cpp/test/test_tlsf.cpp
Nightly build farm [complaining](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/215/warnings23Result/new/) about the unused variable `iterations`.
Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>
> Fix clang thread safety warning

- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
- tlsf_cpp/test/test_tlsf.cpp
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
> code style only: wrap after open parenthesis if not in one line

- rttest/README.md
- rttest/include/rttest/rttest.h
- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
Fixes https://github.com/ros2/realtime_support/issues/87
* Add -d to set max dynamic memory prefaulting size.
In old version it did preallocation till prefaulter vector
reached the size of char array. Then vector reallocated
(2x) in new memory and leaves old memory free, which
causes char array to be put into this memory and
does not cause page fault. In new implementation,
vector already preallocated with requred size,
which will prevent vector reallocations.
* Fix issue with b,kb,mb,gb units parsing.
* Fix in README actual stack size is 1MB (not 1024MB).
> Make dynamic prefault memory size configurable

- rttest/include/rttest/rttest.h
- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
That way it works on 32-bit as well.
This should fix the build warnings on armhf: https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/409/warnings23Result/new/ .  @r7vme FYI
> Use a uint64_t to store the prefault_dynamic_size.

- rttest/src/rttest.cpp
> Use std::bind instead of deprecated std::bind2nd

- rttest/include/rttest/utils.h
- rttest/include/rttest/utils.hpp
- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
UT is passed in 64bit(x86_64) and 32bit(Raspberry Pi).
> Convert timespec to uint64 not long and vice versa  (#94)

- rttest/CMakeLists.txt
- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
This PR enables `-Wall`, `-Wextra`, and `-Wpedantic` and modifies the code to fix thrown warnings.
> Enable basic warnings in rttest

- rttest/src/rttest.cpp
On Linux release builds, we are getting a new warning from rttest saying
that the strcpy wasn't properly 0-terminating the string.
It is actually a false warning (since we are terminating it
on the line before), but it turns out that we can simplify
this whole thing by using strdup.  Do that here.
Fixes #101
> Use strdup instead of strlen/strcpy dance.

- rttest/src/rttest.cpp
This gets rid of some brittle hand-management of the pointers,
which should both make this more robust and also fix some
lingering clang static analyzer errors.
> Convert the sample buffer to a vector.

- rttest/src/rttest.cpp
One cleanup that we missed while changing rttest_sample_buffer
to a class.
> Remove "struct" from rttest_sample_buffer variable declaration.

- tlsf_cpp/package.xml
The files in here are marked as Apache 2.0, so we should have
the license tag for that.  Since it links against the tlsf
library which is LGPL, we leave the tag for that as well.
Fixes #106
> Add in the Apache license to tlsf_cpp.

- tlsf_cpp/test/test_tlsf.cpp
glibc 2.34 completely removed the malloc hooks, since they
were brittle and prone to abuse.  It turns out that despite
all of the infrastructure in the tlsf_cpp tests, we weren't
actually using the results at all, so we can safely completely
remove it here.
> Remove the use of malloc hooks from the tlsf_cpp tests.

- rttest/CMakeLists.txt
- tlsf_cpp/CMakeLists.txt
Part of ament/ament_cmake#365
This makes rttest and tlsf_cpp export modern CMake targets instead of old-style CMake variables.
> Export modern CMake targets

- rttest/CMakeLists.txt
Required for ros2/rmw_implementation#201 which fixes a rolling CI job failure caused by ros2/rmw_cyclonedds#357
The linked libraries don't need to be exported to downstream targets. Doing so causes them to fail to build if they don't also `find_package()` them, especially `Threads::Threads`. The other two libraries are linker only calls, so they can be `PRIVATE` because it's enough that `rrtest` linked to them. Downstream libraries don't need to link to them again.
> Mark dependencies as PRIVATE

- rttest/src/rttest.cpp
Relates to https://github.com/ament/ament_lint/pull/324
> Fix include order for cpplint

- rttest/CMakeLists.txt
- tlsf_cpp/CMakeLists.txt
Part of ros2/ros2#1150 - this installs headers to a unique directory in a merged workspace
I also fixed a couple dependency issues in tlsf_cpp that caused includes to not be found after removing the `include_directories()` call.
> Install headers to include/${PROJECT_NAME}

- rttest/CMakeLists.txt
- rttest/README.md
- rttest/examples/CMakeLists.txt
- tlsf_cpp/CMakeLists.txt
Correcting installation locations for scripts as well as updating the example to use the modern CMake targets.
Found via osrf/ros2_test_cases#211, osrf/ros2_test_cases#221 osrf/ros2_test_cases#223
> Addressing issues found in Humble testing

- tlsf_cpp/CMakeLists.txt
The main reason to do this is so that we can compile the realtime support with the clang static analyzer.  As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version.  So set this as well.
> Update realtime support to C++17.

- tlsf_cpp/CMakeLists.txt
- tlsf_cpp/test/test_tlsf.cpp
We only need to build the test once, and then we can use the RMW_IMPLEMENTATION environment variable to run it for various RMWs.
> Reduce the number of files we compile.

- rttest/CMakeLists.txt
The 'BSD' variable was [added in CMake 3.25](https://cmake.org/cmake/help/latest/variable/BSD.html). Note that variables which are not defined will evaluate to 'False', so this shouldn't regress platforms using CMake versions older than 3.25.
> Don't try to build on BSD
