- src/rttest.cpp
In a follow-up PR for the realtime demo, I will also remove the suggestion to run the process as sudo. I don't think this is a good idea because the user's configuration will not be correct (environment variables such as OSPL_HOME will be unset). At least, that's what happened when I tested running the demo as sudo.
The current behavior for `lock_and_prefault_dynamic` should be to notify the user but not to throw an exception or exit if the lock and prefault function runs out of resources.
> Recover more gracefully from memory errors

- CMakeLists.txt
- README.md
- examples/CMakeLists.txt
- examples/example_loop.c
- include/rttest/rttest.h
- scripts/analyze.py
- scripts/rttest_plot
- src/rttest.cpp
- test/test_api.cpp
Changes made for data collection presented at ROSCon.
> Allow test to run indefinitely, add histogram plotting

- include/rttest/utils.h
Replace unsigned long with uint32_t
Connects to ament/ament_lint#34
> Replace unsigned long with uint32_t

- CMakeLists.txt
- include/rttest/rttest.h
- include/rttest/utils.h
- scripts/analyze.py
- src/rttest.cpp
- test/test_api.cpp
This will also fix a few uncrustify and pyflakes errors that came up from the last large PR made to this repo.
> Correct style to comply with cpplint

- include/rttest/utils.h
Fix cpplint warning
https://github.com/ros2/ros2/issues/12
> Fix cpplint warning

- tlsf_cpp/test/test_tlsf.cpp
this is causing a CI failure on master.
> Fix whitespace

- tlsf_cpp/test/test_tlsf.cpp
Update stacktrace parser for FastRTPS symbols.
> Update for fastrtps

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
> Refactor for executor arguments change

- tlsf_cpp/CMakeLists.txt
Same change as https://github.com/ros2/examples/pull/92
> Use target suffix for rclcpp

- rttest/CMakeLists.txt
- tlsf_cpp/CMakeLists.txt
Connect to ament/ament_cmake#68
> use CTest BUILD_TESTING

- tlsf_cpp/CMakeLists.txt
>  Ensure using correct rmw implementation in tests

- rttest/CMakeLists.txt
- tlsf_cpp/CMakeLists.txt
This disables the RT packages on Android.
> Disable on Android

- tlsf_cpp/CMakeLists.txt
Connect to ament/ament_cmake#72
> require CMake 3.5

- tlsf_cpp/CMakeLists.txt
> add tlsf prefix to allocator_example target

- tlsf_cpp/CMakeLists.txt
> fix spelling error in target suffix

- tlsf_cpp/CMakeLists.txt
> use rmw implementation

- rttest/scripts/analyze.py
Connects to ament/ament_lint#53
> Comply with flake8 + flake8-import-order linters

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
> pass namespace to rclcpp::Node constructors

- rttest/scripts/analyze.py
- rttest/scripts/rttest_plot
> update style to satisfy new flake8 plugins

- rttest/include/rttest/rttest.h
- rttest/include/rttest/utils.h
- rttest/src/rttest.cpp
- rttest/test/test_api.cpp
- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/include/tlsf_cpp/tlsf.hpp
- tlsf_cpp/test/test_tlsf.cpp
Connect to ament/uncrustify#18.
> update style to match latest uncrustify

- tlsf_cpp/test/test_tlsf.cpp
> Add cli args to Node constructor

- tlsf_cpp/test/test_tlsf.cpp
> Pass initial parameter values to node constructor

- tlsf_cpp/example/allocator_example.cpp
Missing return code for int main().
> Fix non return code issue for main() function

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
connects to ros2/demos#185 
fixes ros2/build_cop#125
the related comment here:
https://github.com/ros2/build_cop/issues/125#issuecomment-397820062
> comply with new rclcpp subscription templates

- rttest/package.xml
- tlsf_cpp/package.xml
> Update the maintainer to clalancette

- rttest/package.xml
- tlsf_cpp/package.xml
PR opened for visibility. Fast-forwarding this onto master directly.
> Prepare 0.5.0

- tlsf_cpp/test/test_tlsf.cpp
Connects to ament/uncrustify#24
> fix spacing to comply with uncrustify 0.67

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
Connects to [ros2/rclcpp#492](https://github.com/ros2/rclcpp/issues/492)
> Update for NodeOptions Node constructor

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
connects to ros2/rclcpp#673
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
> Change use of deprecated rclcpp APIs

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
> avoid deprecated publish signature

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
> changes to avoid deprecated API's

- rttest/CMakeLists.txt
> Remove non-package from ament_target_dependencies()

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
This PR is required due to the changes to the intra-process manager in https://github.com/ros2/rclcpp/pull/778
Connects to ros2/rclcpp#778
> Fix Intra-Process API

- tlsf_cpp/example/allocator_example.cpp
- tlsf_cpp/test/test_tlsf.cpp
> avoid new deprecations

- rttest/include/rttest/rttest.h
- rttest/src/rttest.cpp
Links to https://github.com/ament/uncrustify_vendor/pull/27 ; see that PR for more information and CI.
> Fixes for uncrustify 0.72
